name: vstock
description: "Inventory Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.19.0
  dio: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/lang/cs.json
    - assets/lang/vi.json
    - assets/lang/en.json
    - assets/flags/cz.png
    - assets/flags/vn.png
    - assets/flags/en.png
